### ISSUE TITLE
testing/development strategy for support beyond Intel

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang-nursery/stdsimd#13]
Other than the vendor independent interface, this repo only contains vendor intrinsics for Intel. We will of course want to add intrinsics from other vendors on different platforms (like ARM), but I'm not quite sure how to go about it. For the most part, I'd expect it to be a relatively similar process as the Intel intrinsics, but I've held off from doing it because I don't have any systems in place for testing or development of intrinsics on other platforms.

For testing, I assume this means getting CI setup so that it runs on the various platforms that we're targeting.

For development, I'm less sure. I'd like to be able to test, say, ARM intrinsics from the comfort of my local machine. Does this mean running a VM? Or is there something better?

**Comment by mattico** [comment]
[compiler-builtins](https://github.com/rust-lang-nursery/compiler-builtins) uses Docker to run tests inside of QEMU. There are occasionally some spurious failures which seem like they may be QEMU bugs, but otherwise it works fine.

That specific solution uses the host `rustc` inside the docker container so the host must be linux. If you installed rust inside the container it would be pretty straightforward to run anywhere you can install docker.

**Comment by BurntSushi** [comment]
@mattico Awesome! That does indeed sound promising.
