### ISSUE TITLE
`.into()` is very slow

### ISSUE THREAD

**Issue by quininer** [rust-lang-nursery/stdsimd#215]
* rustc 1.23.0-nightly (246a6d19c 2017-11-23)
* CPU: Intel i7-6700HQ (8)

I am trying to [use `coresimd` in `gimli-permutation`](https://github.com/quininer/gimli/blob/5f512d1cbb5c38a915ee8758be436754f3f19be3/gimli-permutation/src/sse.rs#L19), but it very slow.

![screenshot_20171124_153814](https://user-images.githubusercontent.com/6286761/33199956-85b5dfe8-d12d-11e7-8fcc-f64db3dacc96.png)

I found a lot of `Into` is not optimized.

```rust
            x = _mm_shuffle_epi8(
                x.into(),
                _mm_set_epi8(12, 15, 14, 13, 8, 11, 10, 9, 4, 7, 6, 5, 0, 3, 2, 1).into()
            ).into();
            y = (shift(y.into(), 9) | _mm_srli_epi32(y.into(), 32 - 9)).into();
            let newz = x.as_i32x4() ^ shift(z.into(), 1)    ^ shift((y & z).into(), 2);
            let newy = y            ^ x                     ^ shift((x | z).into(), 1).into();
            x = z ^ y ^ shift((x & y).into(), 3).into();
```

![index](https://user-images.githubusercontent.com/6286761/33199998-bab0456c-d12d-11e7-8c60-84bc915268b9.png)

I don't know if this should be a rust issue, so I report it here.

**Comment by BurntSushi** [comment]
Please provide a reproducible example that we can easily compile and test. Please also tell us how you're compiling your code. For example, are you using codegen units or incremental compilation? Are you compiling in release mode?

**Comment by gnzlbg** [comment]
Since those are `cargo bench` results I assume that is `release` mode but it would be good to know if you have a custom `bench` profile in your `Cargo.toml`. 

@BurntSushi I will try to send a PR with the bench to `stdsimd` so that we can either add it or easily look at it, but I am fully booked till sunday.

@quininer how urgent is this?

**Comment by quininer** [comment]
@BurntSushi Yes, I use incremental compilation.

@gnzlbg It is less urgent, I currently use `transmute` instead of `Into`.

**Comment by gnzlbg** [comment]
@quininer have you tested with the `.as_` methods?

**Comment by alexcrichton** [comment]
The bug here is incremental compilation which is known to decrease performance in release mode. The problem here is that function calls are being made, which means that these are happening in different codegen units as inlining is prevented. This is probably because `Into::into` (the blanket impl) is just `#[inline`] instead of `#[inline(always)]` whereas the `From` impls generated in the crate are indeed tagged with `#[inline(always)]`

Your two possible courses of action are:

* Switch to using `iNNxYY::from(...)` instead of `.into()` (as terribly unergonomic as that is...)
* Enable ThinLTO or wait for ThinLTO to stabilize

Other than that though there's not much we can do about this, it's just how incremental compilation in release mode works right now (performance gets worse in some cases)

**Comment by quininer** [comment]
@gnzlbg `.as_*` works fine.

**Comment by gnzlbg** [comment]
That's suspicious, `.into()` should IMO work fine as well. @alexcrichton we should re-open this. I won't be able to look into this today, but I will check it out on sunday.

**Comment by alexcrichton** [comment]
No as I mentioned, `into` is not tagged `#[inline(always)]`, that's why it's not inlined when using incremental compilation.

**Comment by gnzlbg** [comment]
We are implementing `From` in this crate for the types, could we maybe work around that by implementing `Into` as well (and adding `#[inline(always)]` to our implementation) ? `Into` is implemented already for everything that implements `From` but maybe we could use specialization here to override that.

**Comment by alexcrichton** [comment]
Unfortunately coherence won't allow that

**Comment by gnzlbg** [comment]
Shouldn't we make that impl from `Into` `#[inline(always)]` in general then? And leave it to `From` whether things should be inlined or not?

**Comment by gnzlbg** [comment]
> Unfortunately coherence won't allow that

If the `Into` trait `impl` for `From` would mark `into` as `default` then coherence would allow that. 

We define the SIMD types here, so we can specialize blanket impls of traits we don't define for those types here as long as they are specializable.

**Comment by alexcrichton** [comment]
Sorry but I think this is bring approached from the wrong angle. I believe it is not our job to fix this at all costs. This has been diagnosed and there are a number of reasonable workarounds. This will be fixed in the future with ThinLTO. I'd rather not spend more time debating various solutions for this.

**Comment by gnzlbg** [comment]
Makes sense. I tried a couple of things this morning to address this but I
couldn’t really find anything we can reasonably do that always works.

IMO the best thing we could do is add a small benchmark for this once it is
fixed upstream to prevent upstream from breaking this in the future (but
arguably we should just check that this is the case in rustc once LTO is
merged).

Sorry for the noise.
