### ISSUE TITLE
Native auxv support

### ISSUE THREAD

**Issue by lu-zero** [rust-lang-nursery/stdsimd#243]
This is a followup on the minimal support for it that got recently merged.

The ELF auxiliary vector contains useful information to figure out the hardware capabilities enabled.

In general the auxiliary vector is a key-value list that is mapped next to the to the `environ`.

Just walking the stack starting from the environ pointer is valid only if a previous call of `setenv` does not force the reallocation of the environment array.
Walking from the `argv` pointer should be always valid, but it is more difficult to save it. (see the `lang_start` trick used by `std`)

On Linux there are a number of different ways to access it:
- using the `getauxval` non-standard library function 
- reading the `/proc/self/auxv` pseudo-file

Sometimes `/proc/self` is not readable, sometimes `getauxval` is not present depending on the `libc` implementation.

non-linux ELF system may have other facilities to reach the vector.

- [ ] try to get the getauxval binding from the `auxv` crate integrated in stdsimd.
- [ ] discuss further if would be worthy save the `auxv` pointer the same way `argv` is saved.

**Comment by gnzlbg** [comment]
This is more or less how the run-time feature detection for ARM, PowerPC, etc. already works. 

First try to call `getauxval`. If the function does not exist (for example, because it is not linked), then try to read `/proc/self/auxv` and parse the result. If the file is not readable(for example, because it does not exist), then it tries to read and parse `/proc/cpuinfo`.
