### ISSUE TITLE
_mm256_castpd_si256 and other intrinsics aren't a transmute

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/stdsimd#285]
According to [intel](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=AVX&text=_mm256_castpd_si256&expand=586,610,608,586) intrinsics like `_mm256_castpd_si256` are noops, but right now they're implemented as casts for us. According to clang docs I think they're supposed to be bitwise transmutes?

I'm fixing this in a local branch of mine, but wanted to be sure to log this. So far the intrinsics are:

* `_mm256_castpd_si256`
* `_mm256_castsi256_pd`

**Comment by gnzlbg** [comment]
This is how clang does it:

```c++
static __inline __m256i __DEFAULT_FN_ATTRS
_mm256_castpd_si256(__m256d __a)
{
    return (__m256i)__a;
}

static __inline __m256d __DEFAULT_FN_ATTRS
 _mm256_castsi256_pd(__m256i __a)
{
    return (__m256d)__a;
}
```

Those `(__m256{i,d})value` are C-like cast, that is, when a `static_cast` fails (a type-safe `mem::transmute`/`Deref`) because there isn't an appropriate type-safe conversion, the cast falls back to a `const_cast` (making `const` variables non-const, and doing a `static_cast` again), and when that fails, it falls back to a `reinterpret_cast`, which does just an unsafe `mem::transmute`. If that fails the cast fails, no `dynamic_cast` is performed.

It's hard to tell locally from those pieces of code which of the casts is triggering, but because there are no `const`s involved, either a `static_cast` or a `reinterpret_cast` which since these are builtin types, are probably just a `mem::transmute`.

**Comment by alexcrichton** [comment]
Yeah I was reading clang as well to try to square this, and I also wasn't able to interpret what clang was doing from the source :)

What I did notice from clang though was documentation like:

```
/// \returns A 256-bit integer vector containing the same bitwise pattern as the
///    parameter.
```

and 

```
/// \returns A 256-bit floating-point vector of [4 x double] containing the same
///    bitwise pattern as the parameter.
```

which makes me think that the casts here may not be like other integer casts in C?
