### ISSUE TITLE
Question: Why _mm256_xor_si256(a, b) use `vxorps` instead of `vpxor`

### ISSUE THREAD

**Issue by kamyuentse** [rust-lang-nursery/stdsimd#302]
From the Intel specs, `_mm256_xor_si256(a, b)` should use `vpxor`

```
__m256i _mm256_xor_si256 (__m256i a, __m256i b)
#include "immintrin.h"
Instruction: vpxor ymm, ymm, ymm
CPUID Flags: AVX2
```

But I notice that we use `vxorps`
https://github.com/rust-lang-nursery/stdsimd/blob/master/coresimd/src/x86/i586/avx2.rs#L2852

In some platform, they have different CPI.

PS: Feel free to close this if this not reasonable.

**Comment by gnzlbg** [comment]
This might be related to https://github.com/rust-lang-nursery/stdsimd/blob/68542d9b249332e989e7e08dd0c23211a451edab/coresimd/src/x86/i686/mmx.rs#L24

**Comment by kamyuentse** [comment]
Hm... Is bug related to  LLVM of generating target code?

**Comment by gnzlbg** [comment]
This is what clang does:

```c++
static __inline__ __m256i __DEFAULT_FN_ATTRS
_mm256_xor_si256(__m256i __a, __m256i __b)
{
  return (__m256i)((__v4du)__a ^ (__v4du)__b);
}
```

So it looks like the current implementation is doing the same thing:

```rust
/// Compute the bitwise XOR of 256 bits (representing integer data)
/// in `a` and `b`
#[inline(always)]
#[target_feature(enable = "avx2")]
#[cfg_attr(test, assert_instr(vxorps))]
pub unsafe fn _mm256_xor_si256(a: __m256i, b: __m256i) -> __m256i {
    mem::transmute(simd_xor(a.as_i64x4(), b.as_i64x4()))
}
```

The `.as_i64x4` is just a transmute. [Clang generates a `vxorps` instruction as well](https://godbolt.org/g/NJLhgv):

```asm
        push    rbp
        mov     rbp, rsp
        and     rsp, -32
        sub     rsp, 32
        vmovaps ymm0, ymmword ptr [rbp + 48]
        vxorps  ymm0, ymm0, ymmword ptr [rbp + 16]
        mov     rsp, rbp
        pop     rbp
        ret
```

However, if I modify that example to execute some code in the integer domain, then [clang generates `vpxor` as expected](https://godbolt.org/g/U2ncfs):

```asm
        push    rbp
        mov     rbp, rsp
        and     rsp, -32
        sub     rsp, 32
        vmovdqa ymm0, ymmword ptr [rbp + 16]
        vpaddq  ymm1, ymm0, ymmword ptr [rbp + 48]
        vpxor   ymm0, ymm1, ymm0
        mov     rsp, rbp
        pop     rbp
        ret
```

So I'd say this works as expected. That is, LLVM will generate `vpxor` or `vxorps` depending on what's faster and independently of which intrinsic you use. The only issue here is that LLVM seems to prefer `vxorps` over `vpxor` when this intrinsic is used completely out-of-context, but since this is not a realistic situation (the intrinsic will always be used in some context) I don't think this is something worth fixing.

I have added this information to: https://bugs.llvm.org/show_bug.cgi?id=35869 

and am leaving this bug open for now because we should add a comment about this in the code. 

@alexcrichton shouldn't the simd-verify system have detected this?

**Comment by gnzlbg** [comment]
So the reason `vxorps` is preferred over of `vpxor` is because the instruction size is smaller, so completely out-of-context LLVM optimizes here for code-size. 

There is a stale LLVM patch to fix this: https://reviews.llvm.org/D7401

I think this information should be enough to write a comment about this and close this issue. 

I am going to open a more general issue to follow that LLVM patch.

**Comment by alexcrichton** [comment]
@gnzlbg nah unfortunately simd-verify isn't verifying what instructions are asserted right now, we're just asserting that the signature matches Intel's signature. (aka the "why didn't simd-verify catch this" I think is https://github.com/rust-lang-nursery/stdsimd/issues/271)

**Comment by alexcrichton** [comment]
I'm gonna close this in favor of https://github.com/rust-lang-nursery/stdsimd/issues/303, but please feel free to correct me if that's a mistake!
