### ISSUE TITLE
revise #[inline(always)] vs #[inline]

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#340]
With ThinLTO `#[inline(always)]` should not be necessary anymore, most of its uses can be just `#[inline]`.

**Comment by alexcrichton** [comment]
FWIW this was already done for all the vendor intrinsics, and I think it'll work to just switch everything to `#[inline]`

**Comment by gnzlbg** [comment]
So i've change all uses of #[inline(always)] to #[inline] in #338

**Comment by jasondavies** [comment]
I just ran into some issues relating to lack of inlining. In order to test the SHA extensions work, I've converted some C code to Rust (it's mostly just calls to SSE/SHA intrinsics).  However, a couple of SSE intrinsics were not being inlined and caused a 2x slowdown relative to the original C code.  I determined the lack of inlining by manually inspecting the generated assembly.

Changing to `#[inline(always)]` on these couple of intrinsic functions fixed the slowdown issue.  The intrinsics were:

* `_mm_blend_epi16`
* `_mm_alignr_epi8`

I'm using `nightly (75af15ee6 2018-03-20)`.

**Comment by gnzlbg** [comment]
@jasondavies Thanks for

**Comment by gnzlbg** [comment]
You can try that with `RUSTFLAGS=-C lto=fat" cargo build/test --release`

**Comment by jasondavies** [comment]
Sorry, forgot to include that: yes, I'm using `--release` (I created a new example in `examples/` for testing): `cargo build --release --examples`.

I tried `RUSTFLAGS="-C lto=fat" cargo build --release --examples` just now and it did not resolve the slowdown issue.

**Comment by gnzlbg** [comment]
Ok one final question, are you using `stdsimd`, or the simd facilities via `std`/`core` ? 

If you are using the simd facilities via `std`/`core`, could you try if using `stdsimd` with LTO enabled solves your issue? If it doesn't, it would be cool if you have a github repo were you could just push a branch that we can use to reproduce this, or if you prefer, if you could post a minimal working example (e.g. in the playground) that reproduces the issue.

**Comment by alexcrichton** [comment]
If intrinsics aren't being inlined it's almost for sure due to mismatched target features enabled on functions rather than `#[inline]` vs `#[inline(always)]`. @jasondavies are you sure that the function you'd like them inlined into has enabled the right features? If so, is there something we could poke around to see the codegen of?

**Comment by gnzlbg** [comment]
+1 to what @alexcrichton said: if you call, for example, an AVX function from an SSE one, the AVX function will never be inlined.

**Comment by jasondavies** [comment]
Ah, that could be it!  I'm using `stdsimd`.  My example code is [here](https://github.com/jasondavies/stdsimd/blob/sha/examples/beacon.rs).  So I guess I need to enable some more target features.

**Comment by jasondavies** [comment]
Yes, that fixed it.  Thanks!

**Comment by alexcrichton** [comment]
Awesome, good to know!
