### ISSUE TITLE
Boolean vectors should use hand-tuned any() and all()

### ISSUE THREAD

**Issue by hsivonen** [rust-lang-nursery/stdsimd#362]
Thank you for adding portable SIMD and boolean vectors!

In `stdsimd`, `any()` and `all()` are based LLVM cross-ISA on bitwise reductions across the vector, so these operations fail to use the type system information that is the reason for their existence: The information that all the bits of each lane are the same. I.e. in `b8x16`, each lane is either 0 or 0xFF.

This means that looking at all the bits is unnecessary, since for each lane, examining any one bit is sufficient. In the SSE2 case, `_mm_movemask_epi8` takes one bit from each lane of a `u8x16`. It's what the `simd` crate uses.

I've uploaded a [demo crate](https://github.com/hsivonen/anyall) that exports uninlined versions of `any()` and `all()` on `u8x16` using both `simd` and `stdsimd`. The generated code for the `simd` crate versions is much simpler. Code generated using `stdsimd` should be as good.

```asm
    .text
    .file   "anyall0-66776763bbd7db1b14e447f414e2cf9a.rs"
    .section    .text.stdsimd_any_8x16,"ax",@progbits
    .globl  stdsimd_any_8x16
    .p2align    4, 0x90
    .type   stdsimd_any_8x16,@function
stdsimd_any_8x16:
    .cfi_startproc
    movdqa  (%rdi), %xmm0
    pshufd  $78, %xmm0, %xmm1
    por %xmm0, %xmm1
    pshufd  $229, %xmm1, %xmm0
    por %xmm1, %xmm0
    movdqa  %xmm0, %xmm1
    psrld   $16, %xmm1
    por %xmm0, %xmm1
    movdqa  %xmm1, %xmm0
    psrlw   $8, %xmm0
    por %xmm1, %xmm0
    movd    %xmm0, %eax
    testb   %al, %al
    setne   %al
    retq
.Lfunc_end0:
    .size   stdsimd_any_8x16, .Lfunc_end0-stdsimd_any_8x16
    .cfi_endproc

    .section    .text.stdsimd_all_8x16,"ax",@progbits
    .globl  stdsimd_all_8x16
    .p2align    4, 0x90
    .type   stdsimd_all_8x16,@function
stdsimd_all_8x16:
    .cfi_startproc
    movdqa  (%rdi), %xmm0
    pshufd  $78, %xmm0, %xmm1
    pand    %xmm0, %xmm1
    pshufd  $229, %xmm1, %xmm0
    pand    %xmm1, %xmm0
    movdqa  %xmm0, %xmm1
    psrld   $16, %xmm1
    pand    %xmm0, %xmm1
    movdqa  %xmm1, %xmm0
    psrlw   $8, %xmm0
    pand    %xmm1, %xmm0
    movd    %xmm0, %eax
    testb   %al, %al
    setne   %al
    retq
.Lfunc_end1:
    .size   stdsimd_all_8x16, .Lfunc_end1-stdsimd_all_8x16
    .cfi_endproc

    .section    .text.simd_any_8x16,"ax",@progbits
    .globl  simd_any_8x16
    .p2align    4, 0x90
    .type   simd_any_8x16,@function
simd_any_8x16:
    .cfi_startproc
    movdqa  (%rdi), %xmm0
    pmovmskb    %xmm0, %eax
    testl   %eax, %eax
    setne   %al
    retq
.Lfunc_end2:
    .size   simd_any_8x16, .Lfunc_end2-simd_any_8x16
    .cfi_endproc

    .section    .text.simd_all_8x16,"ax",@progbits
    .globl  simd_all_8x16
    .p2align    4, 0x90
    .type   simd_all_8x16,@function
simd_all_8x16:
    .cfi_startproc
    movdqa  (%rdi), %xmm0
    pmovmskb    %xmm0, %eax
    cmpl    $65535, %eax
    sete    %al
    retq
.Lfunc_end3:
    .size   simd_all_8x16, .Lfunc_end3-simd_all_8x16
    .cfi_endproc


    .section    ".note.GNU-stack","",@progbits
```

**Comment by gnzlbg** [comment]
Thanks for the report @hsivonen, this is pretty much expected at this point. 

The problem here is that `b8x16` is actually just an `<i8 x 16>` llvm vector. Because you can transmute any other `<i8 x 16>` llvm vector into it, in this particular case, LLVM does not now that it only contains `0xff`s or `0x00`s. 

If I add the following two functions:

```rust
pub fn stdsimd_eq_all_8x16(a: stdsimd::simd::i8x16, b: stdsimd::simd::i8x16) -> bool {
    stdsimd_all_8x16(a.eq(b))
}

pub fn simd_eq_all_8x16(a: simd::i8x16, b: simd::i8x16) -> bool {
    simd_all_8x16(a.eq(b))
}
```

You will see that they "pretty much" generate identical assembly (*). 

While the current implementation makes it trivial to add custom implementations of `and`/`or`/`xor` for the boolean vector types, I'd rather try a bit harder to get LLVM to emit proper code-gen first. If that does not work, then I'll add custom implementations for these.

---

@rkruppe @alexcrichton I suspect that it would be enough to `simd_cast` the boolean vectors into LLVM vectors of type `<i1 x N>`'s in the implementation of `all/none/any` to significantly improve code-gen here.

---

- [ ] (*) The assembly is not identical, but that's probably a different issue. Need to investigate here further.

**Comment by hsivonen** [comment]
> Because you can transmute any other <i8 x 16> llvm vector into it, 

Transmutes are `unsafe`. If the programmer transmutes something to a boolean vector, it's up to the programmer to make sure the invariants of the type are upheld.

The whole point of having boolean vectors is to use the type system to communicate the precondition (all bits on a lane are the same) of `any()` and `all()` to enable guaranteed-`_mm_movemask_epi8`-based `any()` and `all()` on SSE2.

> in this particular case, LLVM does not know that it only contains 0xffs or 0x00s.

It seems more reliable to have manually-written `any()` and `all()`, since LLVM doesn't have the information that boolean vector types are trying to signal.

> just remove the reductions completely (they can be implemented in a crate external

This would be unfortunate. In particular, the ARMv7+NEON implementation is subtle enough that it should be in the standard library to save application programmers from themselves. (It's still unclear to me if I got the [`simd` crate PR](https://github.com/rust-lang-nursery/simd/pull/20) for the ARMv7+NEON versions right.) Also, it would be sad if adding support for SIMD on POWER8 required hunting around the crate ecosystem for outside-`core` implementations of `any()` and `all()` instead of being able to provide implementations in `core`.

**Comment by gnzlbg** [comment]
> Transmutes are unsafe. If the programmer transmutes something to a boolean vector, it's up to the programmer to make sure the invariants of the type are upheld.

As mentioned, the problem is that we are currently not telling LLVM what the invariants on `std::simd`'s boolean vectors are.

> The whole point of having boolean vectors is to use the type system to communicate the precondition (all bits on a lane are the same) of any() and all() to enable guaranteed-_mm_movemask_epi8-based any() and all() on SSE2.

I strongly disagree. That's a consequence of boolean vectors, but it's not the point. `std::simd`'s boolean vectors try offer a way to convey to the optimizer that the code operates on vectors of boolean values, so that the optimizer can choose whatever instructions it deems fit for whatever ISA is being targeted.

This is not something that can be done in a third-party crate, and why it **must** be done in `std`. 

> This would be unfortunate. [...]  it would be sad [...] hunting around the crate ecosystem [...] 
> It seems more reliable to have manually-written any() and all() [...] ARMv7+NEON [...]

Anyone can do this today on nightly:

```rust
pub struct b8x16(std::arch::x86::__m128i);
impl b8x16 { fn all(self) -> { ... } } 
```

put it on a crate, and have it work on stable Rust soon. 

The point of `std` is to allow users to do these things on their crates, not to prevent them from having to use `crates.io` every time they need to do X.

**Comment by alexcrichton** [comment]
@gnzlbg for `any` and `all` it looks like we're using the "experimental" reductions in LLVM, maybe they're just not well tuned yet? Presumably we could go ahead and call the more optimized versions in particular cases, right? (aka the direct intrinsics)

**Comment by rkruppe** [comment]
Yeah the reduction intrinsics are new-ish and originally intended for ARM SVE if I remember correctly, so it wouldn't surprise me if the x86 backend simple doesn't have good lowering for them yet.

**Comment by gnzlbg** [comment]
Here is an update. I've sent a `rustc` PR (https://github.com/rust-lang/rust/pull/48983) and a `stdsimd` PR (#371) that improve the situation from:

```asm
; stdsimd_all_8x16
movdqa  (%rdi), %xmm0
    pshufd  $78, %xmm0, %xmm1
    pand    %xmm0, %xmm1
    pshufd  $229, %xmm1, %xmm0
    pand    %xmm1, %xmm0
    movdqa  %xmm0, %xmm1
    psrld   $16, %xmm1
    pand    %xmm0, %xmm1
    movdqa  %xmm1, %xmm0
    psrlw   $8, %xmm0
    pand    %xmm1, %xmm0
    movd    %xmm0, %eax
    testb   %al, %al
    setne   %al
```

to this

```asm
  pand %xmm0, %xmm1 # xmm0 = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
  pcmpeqb %xmm0, %xmm1
  pmovmskb %xmm1, %eax
  xorl %ecx, %ecx
  cmpl $65535, %eax # imm = 0xFFFF
  movl $-1, %eax
  cmovnel %ecx, %eax
  testb $1, %al
```

which is still far from perfect, but way better than the shuffle sequence that was being generated before. 

The `pand` with ones the subsequente `pcmpeqb` instructions are a no-op if the input is a boolean vector. I've filled an LLVM bug about this here: https://bugs.llvm.org/show_bug.cgi?id=36702 We'll see what happens with that.

**Comment by gnzlbg** [comment]
Also, the workarounds in the `simd` crate should not work when compiling globally without `sse2`  and using `#[target_feature]` to enable it locally. That is:

```rust
#[target_feature(enable = "sse2")]
pub unsafe fn foo(b: bool8ix16) -> bool {
    b.all()
}
```

won't be able to use `pmovmskb` because `cfg(target_feature = "sse2")` inside the `simd` crate is `false`.

Therefore, we can't really workaround these issues in either `rustc` or `stdsimd` without propagating `#[target_feature]` across function calls such that `cfg(target_feature)`s inside them are expanded again with updated feature sets and the functions re-compiled. 

What am I missing?

**Comment by gnzlbg** [comment]
> For my use cases, I care about the 128-bit reductions being fast when everything is compiled with SSE2 enabled or when everything is compiled with NEON enabled.

Sure, I am preparing a PR with workarounds for those. Just be aware that if you start caring about AVX/AVX2 and you can't compile everything with that enabled then you are going to have to manually select which instructions to use until the upstream LLVM bugs are fixed because right now we can't really workaround these anywhere.

**Comment by gnzlbg** [comment]
> if you start caring about AVX/AVX2 and you can't compile everything with that enabled 

Probably not even that. For those using `std::simd`, they might need to actually recompile `std` with avx2 enabled to benefit from this.

**Comment by hsivonen** [comment]
> which arm targets are you using?

Currently, I'm testing on `aarch64-unknown-linux-gnu`, `armv7-unknown-linux-gnueabihf` and occasionally `armv7-unknown-linux-gnueabihf` with `neon` feature added from the command line. The reason why I don't do the latter all the time is that the ARMv7+NEON is [broken](https://github.com/rust-lang-nursery/simd/issues/12) in the `simd` crate and I've been hoping to switch to `stdsimd` instead of fixing that properly.

Mozilla ships with `armv7-linux-androideabi` and additionally builds nightlies but does not yet ship releases with `aarch64-linux-android`.

> I need to check whether they have NEON enabled in rustc by default.

```sh
$ rustc -Z unstable-options --target armv7-linux-androideabi --print target-spec-json | grep features
  "features": "+v7,+thumb-mode,+thumb2,+vfp3,+d16,-neon",
$ rustc -Z unstable-options --target armv7-unknown-linux-gnueabihf --print target-spec-json | grep features
  "features": "+v7,+vfp3,+d16,+thumb2,-neon",
```

C++ code in Firefox for ARMv7 Android is built with NEON unconditionally enabled, so I think Firefox would benefit from Rust re-introducing an ARMv7+NEON target both for Android and GNU/Linux (Android for shipping and GNU/Linux for testing).

**Comment by gnzlbg** [comment]
@hsivonen so I am going to send a PR today that fixes this issue on master, and I want to ask you to try it by using `stdsimd` master branch and let me know if it works.

You won't get good code-gen using `std::simd` unless you recompile standard with neon enabled on both `armv7` and `aarch64` targets. That is, either you need to use `xargo`, or we would need to add two new targets `{armv7,aarch64}neon-unknown-linux-gnu` to rustc somehow (cc @alexcrichton what are our options here?)

**Comment by hsivonen** [comment]
Thanks. I filed an [issue](https://github.com/rust-lang/rust/issues/49897) about NEON-enabled ARMv7 targets and I intend to try to write a PR for it now. (aarch64 should be fine already.)
