### ISSUE TITLE
x86 _rdtsc has wrong return type

### ISSUE THREAD

**Issue by GabrielMajeri** [rust-lang-nursery/stdsimd#559]
This issue is related to the recently stabilised x86 intrinsic function [`_rdtsc`](https://doc.rust-lang.org/core/arch/x86/fn._rdtsc.html)

The issue is that the function is defined to return a signed `i64`. This is in accordance with [Intel's documentation](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=rdtsc&expand=4255,4255&othertechs=TSC). However, that is not how most people define it, including C/C++ compilers.

This is how GCC [defines it](https://github.com/gcc-mirror/gcc/blob/f9547530289255c6a4fb6b56c8efb0bcc5e5e1b3/gcc/config/i386/ia32intrin.h#L112):
```c
extern __inline unsigned long long // < note the return type
__attribute__((__gnu_inline__, __always_inline__, __artificial__))
__rdtsc (void)
{
  return __builtin_ia32_rdtsc ();
}
```

This [Clang example](https://gcc.godbolt.org/z/A833Yz) proves it also defines it as `unsigned long long`.

Now, I'm confused. Since the timestamp counter is a monotonically increasing timer, it wouldn't make sense to return negative values. In fact, I think it is allowed to return values with the most significant bit set (which would make the returned value negative, unless transmuted). Is the mismatch intended?

**Comment by GabrielMajeri** [comment]
@gnzlbg I have raised an issue with Intel about this intrinsics. Hopefully they'll reply and fix their spec.

**Comment by gnzlbg** [comment]
> I have raised an issue with Intel about this intrinsics. Hopefully they'll reply and fix their spec.

So I don't hold my hopes up here because this would be a breaking change, so I'd suspect that nothing will happen. However, Intel and other vendors do send errata and make breaking changes every now and then, and I'm interested in seeing how we would deal with that.

@GabrielMajeri in the mean time, this particular function is defined in the Intel spect as just reading the content of a register, so it doesn't really matter whether the return value is a signed or unsigned integer (or an `[u8; 8]` or whatever) as long as it is 64-bit wide. Its "the user"s job to interpret those bits as appropriate. I don't know what the value of the register "means" when the sign bit is set, but I'd expect it will just be an unsigned integer.

I have a crate in progress to strongly type all intel intrinsics here and expose them using a safe API when possible: https://github.com/gnzlbg/typed_arch I'll take a PR that implemented the rdtsc intrinsics with a "better" and safe API.

**Comment by GabrielMajeri** [comment]
@gnzlbg Well I submitted a comment to [this forum thread](https://software.intel.com/en-us/forums/intel-isa-extensions/topic/363747) which is where the Intrinsics guide told me to post issues to. The comemnt is still waiting for moderator approval, and then I'll wait for a reply from Intel staff.

To me it just looks like an issue with their documentation, considering they did mess up the types in their intrinsics guide before.

**Comment by gnzlbg** [comment]
@GabrielMajeri is there an acknowledgment of the bug or where you contacted about it ? Otherwise it might be worth it to start a new thread there just about that.

**Comment by GabrielMajeri** [comment]
I've tried submitting another message, although it seems the intrinsics guide is not exactly a priority. I wouldn't consider it to be an official _specification_ in any way, just a helpful resource for developers who are looking for documentation on how to use the intrinsics.

**Comment by gnzlbg** [comment]
Sadly, there does not appear to be a real "specification" of Intel compiler C intrinsics beyond the intrinsics guide. I'm going to merge the PR, and try to update stdsimd upstream doing a crater run with it. Maybe we can fix it.
