### ISSUE TITLE
types to use for mask parameters

### ISSUE THREAD

**Issue by jackmott** [rust-lang-nursery/stdsimd#6]
avx and avx512 have a lot of mask parameters.

For a function like `_mm256_blendv_pd` what should the type be for the mask parameter?
I've currently got it as:

``` rust
pub fn _mm256_blendv_pd(a: f64x4, b: f64x4, mask: f64x4) -> f64x4 {
    unsafe { blendvpd256(a, b, mask) }
}
```

But should this be i64x4?  __m256i?

**Comment by BurntSushi** [comment]
This is an interesting one. I'm not exactly sure. Both Clang and the Intel documentation say the mask should be a `__m256d` which is equivalent to `f64x4`. The documentation certainly seems to treat the mask parameter as if it were a normal bit vector, but the types clearly indicate otherwise.

Unless there's a compelling reason to the contrary, we should stick to the vendor interface. I will note this case down and mention in the RFC though. Thanks!

**Comment by alexcrichton** [comment]
@p32blo [had a question](https://github.com/rust-lang-nursery/stdsimd/pull/91#issuecomment-333783129) about some mask types, @BurntSushi you may know better than I maybe?

**Comment by alexcrichton** [comment]
I'm going to close this now due to https://github.com/rust-lang-nursery/stdsimd/issues/263
